services:

  # MC Server World Config
  latechsmp-survival:
    build: .
    container_name: latechsmp-survival
    environment:
      EULA: "true"
      TYPE: PURPUR
      VERSION: "26.2"
      TZ: "America/Chicago"
      MEMORY: "16G"
      USE_AIKAR_FLAGS: "true"
      CREATE_CONSOLE_IN_PIPE: "true"
    ports:
      - "25565:25565/tcp"
      - "24454:24454/udp"
    #  - "25565:25565/udp"
    volumes:
      - ./data:/data
    devices:
      - /dev/net/tun:/dev/net/tun
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - mc_network

  # viaproxy for version compatibility and geyser support
  latechsmp-viaproxy:
    image: ghcr.io/viaversion/viaproxy:latest
    container_name: latechsmp-viaproxy
    volumes:
      - ./viaproxy-data:/app/run
    ports:
      - "25565:19132/udp"     # Bedrock clients connect here via Geyser-ViaProxy plugin, mapped to host 25565
    depends_on:
      - latechsmp-survival
    networks:
      - mc_network
    restart: unless-stopped

  # playit.gg support to allow for tunneling the server
#  latechsmp-playit:
#    image: ghcr.io/playit-cloud/playit-agent:latest
#    network_mode: host
#    container_name: latechsmp-playit
#    depends_on:
#      - latechsmp-survival
#    environment:
#      # in order to use a playit tunnel, you will need to acquire a token
#      - SECRET_KEY={PLAYIT_SECRET_TOKEN}
#    restart: unless-stopped


networks:
  mc_network:
    driver: bridge
